'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function OnboardingV4Ch2() {
  const router = useRouter();
  const [selectedConditions, setSelectedConditions] = useState<string[]>([]);
  const [emergencyContact, setEmergencyContact] = useState('');
  const [emergencyPhone, setEmergencyPhone] = useState('');
  const conditions = [{ id: 'hypertension', label: '고혈압' }, { id: 'diabetes', label: '당뇨' }, { id: 'arthritis', label: '관절염' }, { id: 'dementia', label: '치매' }, { id: 'heart', label: '심장 질환' }, { id: 'none', label: '해당 없음' }];
  const toggleCondition = (id: string) => { if (id === 'none') { setSelectedConditions(['none']); } else { setSelectedConditions(prev => prev.includes(id) ? prev.filter(c => c !== id && c !== 'none') : [...prev.filter(c => c !== 'none'), id]); } };
  const isComplete = selectedConditions.length > 0 && emergencyContact && emergencyPhone;
  const progress = ((selectedConditions.length>0?1:0)+(emergencyContact?1:0)+(emergencyPhone?1:0))/3*100;
  return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-emerald-50 to-green-50 flex items-center justify-center p-6"><div className="max-w-2xl w-full"><div className="mb-6"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-slate-600">진행 상황</span><span className="text-xs font-bold text-teal-600">{Math.round(progress)}%</span></div><div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-teal-600 to-emerald-600 transition-all duration-300" style={{width: `${progress}%`}}></div></div></div>
      <div className="bg-white rounded-3xl shadow-2xl p-10 border-2 border-white/50"><div className="mb-8"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-teal-100 border border-teal-200 mb-4"><span className="w-2 h-2 rounded-full bg-teal-600 animate-pulse" /><span className="text-xs font-bold text-teal-700 uppercase tracking-wide">Version 4 - Step 2/4</span></div><h1 className="text-3xl font-black text-slate-900 mb-2">건강 정보</h1><p className="text-base font-medium text-slate-600">소리가 더 세심하게 대화할 수 있어요</p></div>
        <div className="space-y-6"><div className="p-6 rounded-2xl bg-gradient-to-br from-teal-50 to-emerald-50 border-2 border-teal-200"><h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2"><svg className="w-5 h-5 text-teal-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clipRule="evenodd"/></svg>주요 질환</h3><div className="grid grid-cols-2 gap-3">{conditions.map((condition) => <button key={condition.id} onClick={() => toggleCondition(condition.id)} className={`h-11 rounded-xl font-bold text-xs transition-all duration-200 ${selectedConditions.includes(condition.id) ? 'bg-teal-600 text-white shadow-lg' : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'}`}>{condition.label}</button>)}</div></div>
        <div className="p-6 rounded-2xl bg-gradient-to-br from-blue-50 to-cyan-50 border-2 border-blue-200"><h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2"><svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd"/></svg>긴급 연락처</h3><div className="grid grid-cols-2 gap-3"><input value={emergencyContact} onChange={(e) => setEmergencyContact(e.target.value)} className="h-11 px-4 border-2 border-slate-200 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-sm font-medium" placeholder="이름"/><input value={emergencyPhone} onChange={(e) => setEmergencyPhone(e.target.value)} className="h-11 px-4 border-2 border-slate-200 rounded-xl focus:border-blue-500 focus:ring-2 focus:ring-blue-200 transition-all text-sm font-medium" placeholder="010-0000-0000"/></div></div></div>
        <div className="flex gap-3 mt-8"><button onClick={() => router.push('/onboarding/chapter-1-v4')} className="h-12 px-6 rounded-xl border-2 border-slate-300 text-slate-700 font-bold text-sm hover:bg-slate-50 transition-all duration-200 active:scale-95">이전</button><button onClick={() => router.push('/onboarding/chapter-3-v4')} disabled={!isComplete} className={`flex-1 h-14 rounded-xl font-bold text-sm transition-all duration-200 ${isComplete ? 'bg-gradient-to-r from-teal-600 to-emerald-600 text-white shadow-lg hover:shadow-xl hover:scale-[1.02] active:scale-95' : 'bg-slate-200 text-slate-400 cursor-not-allowed opacity-40'}`}>{isComplete ? '계속 →' : '정보를 입력해주세요'}</button></div></div></div>
    </div>
  );
}
