'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export default function OnboardingV4Ch4() {
  const router = useRouter();
  const [agreed, setAgreed] = useState(false);
  return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-emerald-50 to-green-50 flex items-center justify-center p-6"><div className="max-w-2xl w-full"><div className="mb-6"><div className="flex items-center justify-between mb-2"><span className="text-xs font-bold text-slate-600">진행 상황</span><span className="text-xs font-bold text-teal-600">100%</span></div><div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-teal-600 to-emerald-600 transition-all duration-300" style={{width: '100%'}}></div></div></div>
      <div className="bg-white rounded-3xl shadow-2xl p-10 border-2 border-white/50"><div className="mb-8 text-center"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-teal-100 border border-teal-200 mb-4"><span className="w-2 h-2 rounded-full bg-teal-600 animate-pulse" /><span className="text-xs font-bold text-teal-700 uppercase tracking-wide">Version 4 - 완료!</span></div><h1 className="text-3xl font-black text-slate-900 mb-2">모든 준비 완료!</h1><p className="text-base font-medium text-slate-600">소리가 설정하신 시간에 전화드릴게요</p></div>
        <div className="space-y-6"><div className="p-6 rounded-2xl bg-gradient-to-br from-teal-50 to-emerald-50 border-2 border-teal-200"><h3 className="text-sm font-bold text-slate-700 mb-4">입력하신 정보</h3><div className="space-y-3 text-sm">{['프로필', '건강 정보', '통화 설정'].map(item => <div key={item} className="flex justify-between"><span className="font-semibold text-slate-600">{item}</span><span className="font-bold text-slate-900">완료</span></div>)}</div></div>
        <div className="p-6 rounded-2xl bg-blue-50 border-2 border-blue-200"><label className="flex items-start gap-3 cursor-pointer"><input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} className="mt-1 w-5 h-5 rounded border-2 border-slate-300 text-blue-600 focus:ring-2 focus:ring-blue-500"/><span className="text-sm font-medium text-slate-700 leading-relaxed">개인정보 수집 및 이용에 동의하며, 소리가 안전하게 정보를 관리하는 것을 확인했습니다.</span></label></div></div>
        <div className="flex gap-3 mt-8"><button onClick={() => router.push('/onboarding/chapter-3-v4')} className="h-12 px-6 rounded-xl border-2 border-slate-300 text-slate-700 font-bold text-sm hover:bg-slate-50 transition-all duration-200 active:scale-95">이전</button><button onClick={() => router.push('/dashboard')} disabled={!agreed} className={`flex-1 h-14 rounded-xl font-bold text-sm transition-all duration-200 ${agreed ? 'bg-gradient-to-r from-teal-600 to-emerald-600 text-white shadow-lg hover:shadow-xl hover:scale-[1.02] active:scale-95' : 'bg-slate-200 text-slate-400 cursor-not-allowed opacity-40'}`}>{agreed ? '소리와 함께 시작하기 🎉' : '동의 후 시작'}</button></div></div></div>
    </div>
  );
}
